version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: creaunacontraseñasegura
      MYSQL_DATABASE: proyecto
      MYSQL_USER: user
      MYSQL_PASSWORD: creaunacontraseñasegura
    volumes:
      - ./DumpProyecto.sql:/docker-entrypoint-initdb.d/DumpProyecto.sql
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: app-node
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: creaunacontraseñasegura
      DB_NAME: proyecto
      JWT_SECRET: crea-un-secreto-largo
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules_data:/app/node_modules
    command: node --watch server.mjs

volumes:
  node_modules_data: